// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjo0g4CwNaht6NcPyyRvHCzWC9emY8dmU',
    appId: '1:304215661432:web:ea7b53417e0cbbc9ad068d',
    messagingSenderId: '304215661432',
    projectId: 'ecomm-app-8fb1f',
    authDomain: 'ecomm-app-8fb1f.firebaseapp.com',
    storageBucket: 'ecomm-app-8fb1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBh9MacYPhL42IyJ2cGP2Opz2WCyJzOO0',
    appId: '1:304215661432:android:84493586c881a341ad068d',
    messagingSenderId: '304215661432',
    projectId: 'ecomm-app-8fb1f',
    storageBucket: 'ecomm-app-8fb1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFoR5BO-n-k45o2eVhZIntUqUn4OfBcRc',
    appId: '1:304215661432:ios:06e84e320443032fad068d',
    messagingSenderId: '304215661432',
    projectId: 'ecomm-app-8fb1f',
    storageBucket: 'ecomm-app-8fb1f.appspot.com',
    iosBundleId: 'com.example.blocFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFoR5BO-n-k45o2eVhZIntUqUn4OfBcRc',
    appId: '1:304215661432:ios:06e84e320443032fad068d',
    messagingSenderId: '304215661432',
    projectId: 'ecomm-app-8fb1f',
    storageBucket: 'ecomm-app-8fb1f.appspot.com',
    iosBundleId: 'com.example.blocFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjo0g4CwNaht6NcPyyRvHCzWC9emY8dmU',
    appId: '1:304215661432:web:d002e68c85e2b159ad068d',
    messagingSenderId: '304215661432',
    projectId: 'ecomm-app-8fb1f',
    authDomain: 'ecomm-app-8fb1f.firebaseapp.com',
    storageBucket: 'ecomm-app-8fb1f.appspot.com',
  );
}
